### ISSUE TITLE
Dragging does not work

### ISSUE THREAD

**Issue by tyeeman** [BazzaCuda/CustomMenu#23]
I thought I'd try this after your nice ffmpegparams app. I have the config open on my desktop and when I go to drag a shortcut onto it I get a circle with a diagonal line through it meaning it's not working. I'm on Win10. Anything I'm doing wrong? The title bars shows it running as admin. I also get this strange window - 

![2024-05-09_173400_cr](https://github.com/BazzaCuda/CustomMenu/assets/4469306/b47e2af7-be85-48bb-a7ca-07a9831dc407)

**Comment by BazzaCuda** [comment]
Hi, I'm going to need some more information.

I assume you're running the latest version, v1.0.8?

Firstly, just to clarify, when you have the config window open you should be able to drag anything onto the tree panel on the left:
![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/e9b37e18-4654-4dcc-9ba3-c2abd0166b77)

You can also drag individual items (e.g .exe or folder) from Explorer to, for example, the Command and Directory boxes.

In tests, I was able to select everything on my desktop and drop them all on the tree panel in one go - it created all the many menu items required. Also, I was able to drag and drop all the .exe's from my Windows\* installation - If I recall correctly, that was about 250 items.

I'm unable to reproduce any situation where I get the "drop forbidden" symbol (red circle with a diagonal line) - I can drag over any part of the config window without getting that symbol.

Secondly, can you show me the config window entry for that "New Menu Item" you've created, please. How did you create it? And what is "ms-gamingoverly" trying to do? Is it an MS Store app?

Is there anything special or non-standard about that desktop that you've screenshoted? Is it a virtual machine, for example? Does it automatically change the desktop background image at intervals?

**Comment by tyeeman** [comment]
Yes, I'm running the latest. I'm dragging shortcuts from my desktop. I thought you could tell me what that ms-gamingoverlay link was. My new menu items is not there now. No virtual machine. Strange. I should make a video and upload it to youtube so you can see.

**Comment by tyeeman** [comment]
Solved!  After 2 days of reading everything I could find.

I was running Custom Menu from total commander which is running as admin. Windows desktop does not run as admin. DnD from lower elevation to higher elevation is prevented in Windows for security reasons obviously. So if I run Custom Menu from a desktop shortcut the DnD works.

**Comment by BazzaCuda** [comment]
Wow! Well done for working it out.

I have to be honest, I have had User Access Control turned off on all my Windows systems for so many years, I'd forgotten it existed! I would never have supposed it was causing any problems with Custom Menu, and certainly not with the Drag and Drop function.

If you have a folder as a standard menu item, it will be opened in Explorer, or whatever file manager you have running (in my case, Directory Opus). If you want to limit the folder contents to just PDFs, for example, what you're creating is a live/dynamic submenu; in this case you manually create a "browse" menu item as per my examples. 

Let me know how you get on.

**Comment by tyeeman** [comment]
Can you show a screenshot of the config window for this -

Alternatively, you can include subfolders and CustomMenu will become a live disk-browsing facility, with a submenu for every subfolder it finds:

Thanks

**Comment by BazzaCuda** [comment]
To create such menus, you specify "browse" in the command box.
The folder to be browsed is specified in the Directory box.
The Parameters box determines which files and folders will be shown from the folder.

![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/202c80ed-cbc9-46f9-b3cf-d6d9783648c1)

This creates a menu item called "Browse Downloads\". When hovered over with the mouse, a live submenu is displayed showing the contents of my downloads folder:
![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/6a382453-61ad-4e39-8792-7f86bd8e6e88)

Because I have specified "+folders", all folders will be displayed and each folder becomes another submenu which can be hovered over:
![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/92477c7a-5669-471a-8200-8d3805a349c3)

In this case, I have limited the files to be shown as just *.pdf and *.epub. You can also specify `*.*` to show all files (this is the default).



As you move the mouse over the folders, it will helpfully distinguish between those that have contents [which match your criteria] and those that don't:

![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/217e3d05-75de-4fa9-98de-d0e635ec6f2a)

One of the best uses of the browse feature is that I have menu items set up for the most common drive letters that my Windows system assigns to USB sticks, in my case F:, G:, H: and I:

I have a top level menu item called "USB Drives":
![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/db918b55-7a51-4af7-a176-8ab07db4e18e)

Then I have individual "browse" commands for each drive:
![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/433dcfa8-8984-4224-913c-322583e28f20)

When I have inserted a USB stick, a quick hover over the USB drive menu items shows which drives are mounted and which aren't:
![image](https://github.com/BazzaCuda/CustomMenu/assets/22550919/814078df-b058-44df-939f-1b95fee88e2e)

Note that if you save your Custom Menu to the Windows Desktop Menu (with "Write to Desktop Menu"), the "Browse" menu items only work when accessed from Custom Menu, not from the Windows menu, as Windows doesn't understand what to do with the "browse" command.

Hope that helps. Let me know.

**Comment by tyeeman** [comment]
Excellent. I understand now. I suggest adding this to the bottom of your readme.

**Comment by BazzaCuda** [comment]
Yes, if you create a file called "hotkey" in the same folder as the .exe and restart the app, it will prompt you to create a hotkey to activate Custom Menu from anywhere without needing to get to your desktop. I'll have a think about adding a menu item to the system tray icon.
